---
- name: Validate parameters
  ansible.builtin.assert:
    that:
      - puppeteers_postiz_system_user is string
      - puppeteers_postiz_system_user_home is string
      - puppeteers_postiz_ssh_authorized_key is string
      - puppeteers_postiz_podman_quadlets_repo is string
      - puppeteers_postiz_podman_quadlets_repo_version is string
      - puppeteers_postiz_postiz_postgresql_user is string
      - puppeteers_postiz_postiz_postgresql_db is string
      - puppeteers_postiz_postiz_postgresql_password is defined
      - puppeteers_postiz_temporal_postgresql_user is string
      - puppeteers_postiz_temporal_cors_origins is string
      - puppeteers_postiz_temporal_postgresql_password is defined
      - puppeteers_postiz_main_url is string
      - puppeteers_postiz_frontend_url is string
      - puppeteers_postiz_next_public_backend_url is string
      - puppeteers_postiz_backend_internal_url is string
      - puppeteers_postiz_jwt_secret is defined
      - puppeteers_postiz_disable_registration is boolean

- name: Create system user for postiz
  ansible.builtin.user:
    state: present
    name: "{{ puppeteers_postiz_system_user }}"
    comment: User for running postiz in rootless podman containers
    create_home: true

- name: Create .ssh directory for postiz user
  ansible.builtin.file:
    state: directory
    path: "{{ puppeteers_postiz_system_user_home }}/.ssh"
    owner: "{{ puppeteers_postiz_system_user }}"
    group: "{{ puppeteers_postiz_system_user }}"
    mode: "0700"

- name: Add authorized key for postiz user
  ansible.builtin.copy:
    content: "{{ puppeteers_postiz_ssh_authorized_key }}\n"
    dest: "{{ puppeteers_postiz_system_user_home }}/.ssh/authorized_keys" 
    owner: "{{ puppeteers_postiz_system_user }}"
    group: "{{ puppeteers_postiz_system_user }}"
    mode: "0600"
  when: puppeteers_postiz_ssh_authorized_key | length > 0

- name: Enable lingering for postiz user
  ansible.builtin.command:
    cmd: "loginctl enable-linger {{ puppeteers_postiz_system_user }}"

- name: Ensure that prerequisites are installed
  ansible.builtin.package:
    name:
      - podman
      - rsync
      - git
    state: present

- name: Install acl to ensure that Ansible is able to run as postiz user
  ansible.builtin.package:
    name: acl
    state: present

- name: Download container images from Docker Hub by default to avoid interactive prompts
  ansible.builtin.lineinfile:
    state: present
    regexp: "^unqualified-search-registries = "
    line: "unqualified-search-registries = [\"docker.io\"]"
    path: /etc/containers/registries.conf

- name: Get postiz-podman-quadlets repository
  ansible.builtin.git:
    repo: "{{ puppeteers_postiz_podman_quadlets_repo }}"
    version: "{{ puppeteers_postiz_podman_quadlets_repo_version }}"
    dest: "{{ puppeteers_postiz_system_user_home }}/postiz-podman-quadlets"

- name: Get the uid for the postiz user
  ansible.builtin.command:
    cmd: "id -u {{ puppeteers_postiz_system_user }}"
  register: postiz_id_cmd

- name: Store id of postiz user
  ansible.builtin.set_fact:
    postiz_uid: "{{ postiz_id_cmd.stdout }}"

- name: Create global quadlet directory for the postiz user
  ansible.builtin.file:
    state: directory
    recurse: true
    path: "/etc/containers/systemd/users/{{ postiz_uid }}"
    owner: root
    group: "{{ puppeteers_postiz_system_user }}"
    mode: "0750"

- name: Synchronize quadlets from the repo to the quadlet directory
  ansible.builtin.command:
    cmd: "rsync --chown=root:{{ puppeteers_postiz_system_user }} --recursive --include='*.container' --include='*.volume' --include='*.network' --exclude='*' {{ puppeteers_postiz_system_user_home }}/postiz-podman-quadlets/ /etc/containers/systemd/users/{{ postiz_uid }}/"

- name: Populate container environment files
  ansible.builtin.template:
    src: "{{ postiz_env_file }}.env.j2"
    dest: "/etc/containers/systemd/users/{{ postiz_uid }}/{{ postiz_env_file }}.env"
    owner: root
    group: "{{ puppeteers_postiz_system_user }}"
    mode: "0640"
  loop:
    - postiz
    - postiz-postgresql
    - temporal
    - temporal-admin-tools
    - temporal-elasticsearch
    - temporal-postgresql
    - temporal-ui
  loop_control:
    loop_var: postiz_env_file
  notify:
    - refresh unit file list for postiz user
    - restart postiz unit

- name: Create volumes
  containers.podman.podman_volume:
    state: present
    name: "{{ postiz_volume }}"
  become: true
  become_user: "{{ puppeteers_postiz_system_user }}"
  loop:
    - postiz-config
    - postiz-postgresql
    - postiz-redis
    - postiz-uploads
    - temporal-dynamicconfig
    - temporal-elasticsearch
    - temporal-postgresql
  loop_control:
    loop_var: postiz_volume

- name: Create networks
  containers.podman.podman_network:
    state: present
    name: "{{ postiz_network}}"
    driver: bridge
  become: true
  become_user: "{{ puppeteers_postiz_system_user }}"
  loop:
    - postiz
    - temporal
  loop_control:
    loop_var: postiz_network

- name: Get path to temporal-dynamicconfig volume mountpoint
  containers.podman.podman_volume_info:
    name: temporal-dynamicconfig
  become: true
  become_user: "{{ puppeteers_postiz_system_user }}"
  register: podman_volume_info

- name: Store temporal-dynamicconfig volume mountpoint
  ansible.builtin.set_fact:
    temporal_dynamicconfig_mountpoint: "{{ podman_volume_info['volumes'][0]['Mountpoint'] }}"

- name: Copy development-sql.yaml to temporal-dynamicconfig volume
  ansible.builtin.copy:
    remote_src: true
    src: "{{ puppeteers_postiz_system_user_home }}/postiz-podman-quadlets/dynamicconfig/development-sql.yaml"
    dest: "{{ temporal_dynamicconfig_mountpoint }}/development-sql.yaml"
    owner: "{{ puppeteers_postiz_system_user }}"
    group: "{{ puppeteers_postiz_system_user }}"
    mode: "0644"
  notify:
    - restart temporal unit
