- name: refresh unit file list for postiz user
  ansible.builtin.command:
    cmd: "systemctl --user -M {{ puppeteers_postiz_system_user }}@ daemon-reload"

- name: restart postiz unit
  ansible.builtin.command:
    cmd: "systemctl --user -M {{ puppeteers_postiz_system_user }}@ restart postiz"

- name: restart postiz https proxy unit
  ansible.builtin.command:
    cmd: "systemctl --user -M {{ puppeteers_postiz_system_user }}@ restart postiz-https-proxy"

- name: restart temporal unit
  ansible.builtin.command:
    cmd: "systemctl --user -M {{ puppeteers_postiz_system_user }}@ restart temporal"
